apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
  nodeSelector:
    number: "3"

  tolerations:
  - effect: NoSchedule
    key: "m03Taint"
    value: "true"
    operator: "Equal"
