apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: init-container
spec:
  containers:
  - name: nginx
    image: nginx
  initContainers:
  - name: init-container
    image: nginx
    command: ["/bin/bash","-c","ls"]
